Port to Python CLI
hassanselim0/PassGen pull request #1
Opened 2020-08-11 21:31 UTC by mariamrf

2020-08-11 22:00 UTC, mariamrf commented
There's an issue with the imports. I'll fix it and mark it as ready when it is.

2020-08-11 22:38 UTC, hassanselim0 commented
Thank you so much for your effort, you really went beyond here 😁 (unit tests? PyPI with installing the script in PATH? wow!)

I'll test this over on the weekend, specifically, I'll take my own key list files and make sure the master check and password generation is identical.

In the mean time, can you squash the commits a bit, it feels like after the first 2 commits, it was mostly fixes (typos and so on), so you can do an interactive rebase and reorder commits and mark them as "fixup", so the end result would just be the first 2 commits. (I'm a bit OCD with commits, I know 😅)

2020-08-11 23:55 UTC, mariamrf commented
Commits squashed so it's only 2 now~

2021-01-01 00:42 UTC, hassanselim0 requested changes
hey, I finally got around to reviewing this PR 😅
So I had to do two changes to make it generate identical password to the dotnet-core version and pass master check for files generated by the dotnet-core version.
First I made the Label case-sensitive (remove the `.lower()` lines), second is I changed the `hash_master` function because the result of PBKDF2 was different from the repeated SHA256 I was doing manually.
I realize now that I should really be using PBKDF2 or some other standard key derivation function (maybe Argon2?) as my iteration might actually be making things less secure... I failed to follow my own advice of "never roll your own crypto function", anyways, I'll probably do that for version 2 of the key file 😅

I'm not sure how I can push that commit I made, this is the first time I accept a PR from a branch on a repo I don't have access to, so I just wrote the `hash_master` code change as PR line comment.

2021-01-01 00:42 UTC, hassanselim0 commented on passgen-py/src/utils.py
> +    hashed = pbkdf2_hmac('sha256', password.encode(), salt, iter_count)
```py
hashed = b''
for _ in range(iter_count):
    hashed = sha256(hashed + password.encode() + salt).digest()
```
and remove the now unusued pbkdf2_hmac import

2021-02-20 00:10 UTC, hassanselim0 approved these changes
Ok so I updated my master hashing algorithm to PBKDF2 😅
I'll just merge this then do a commit to make the label case-sensitive 😁

2021-02-20 00:14 UTC, merged